.Dd $Mdocdate$
.Dt MLK_ALLOC_SET 3
.Os
.Sh NAME
.Nm mlk_alloc_set
.Nd allocation routines
.Sh LIBRARY
libmlk-core (-lmlk-core)
.Sh SYNOPSIS
.In mlk/core/alloc.h
.Ft void
.Fn mlk_alloc_set "const struct mlk_alloc_funcs *funcs"
.Sh DESCRIPTION
Change allocation routines for the entire framework and its underlying
libraries.
.Pp
The
.Fn mlk_alloc_set
function changes allocator functions to
.Fa funcs
allocator routines. It must be kept valid until the program is no longer used.
See the
.Xr mlk-alloc 3
manual page for the
.Vt mlk_alloc_funcs
type definition.
.Sh SEE ALSO
.Xr mlk-alloc 3
.Sh AUTHORS
.An David Demelier Aq Mt markand@malikania.fr .
