.Dd $Mdocdate$
.Dt MLK_ACTION_FINISH 3
.Os
.Sh NAME
.Nm mlk_action_finish
.Nd cleanup action resources
.Sh LIBRARY
libmlk-core (-lmlk-core)
.Sh SYNOPSIS
.In mlk/core/action.h
.Ft void
.Fn mlk_action_finish "struct mlk_action *self"
.Sh DESCRIPTION
Invoke the
.Va finish
callback on the action
.Fa self
if it is not null.
.Sh SEE ALSO
.Xr mlk-action 3
.Sh AUTHORS
The
.Nm mlk-core
library was written by
.An David Demelier Aq Mt markand@malikania.fr .
