.Dd $Mdocdate$
.Dt MLK_ACTION_UPDATE 3
.Os
.Sh NAME
.Nm mlk_action_update
.Nd update an action
.Sh LIBRARY
libmlk-core (-lmlk-core)
.Sh SYNOPSIS
.In mlk/core/action.h
.Ft void
.Fn mlk_action_update "struct mlk_action *self, unsigned int ticks"
.Sh DESCRIPTION
Invoke the update callback on the action
.Fa self
if it is not null.
.Sh RETURN VALUES
The functions return the same value as the
.Va update
callback from the action and it should be non-zero if the action is considered
complete.
.Sh SEE ALSO
.Xr mlk-action 3
.Sh AUTHORS
The
.Nm mlk-core
library was written by
.An David Demelier Aq Mt markand@malikania.fr .
