.Dd $Mdocdate$
.Dt MLK_ACTION_HANDLE 3
.Os
.Sh NAME
.Nm mlk_action_handle
.Nd handle an event
.Sh LIBRARY
libmlk-core (-lmlk-core)
.Sh SYNOPSIS
.In mlk/core/action.h
.Ft void
.Fn mlk_action_handle "struct mlk_action *self, const union mlk_event *ev"
.Sh DESCRIPTION
Invoke the
.Va handle
callback on the action
.Fa self
if it is not null with the event
.Fa ev
.Sh SEE ALSO
.Xr mlk-action 3
.Sh AUTHORS
The
.Nm mlk-core
library was written by
.An David Demelier Aq Mt markand@malikania.fr .
